version: 2.1

jobs:
  lint-build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/goutils
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          keys:
            - goutils-deps-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          name: Cache dependencies
          key: goutils-deps-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Build cannon
          command: make build
      - run:
          name: Run tests
          command: make test

workflows:
  lint-build:
    jobs:
      - lint-build
