version: 2.1

jobs:
  lint-test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make setup
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test

workflows:
  lint-test:
    jobs:
      - lint-test
